#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sozluk.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SOZLUK")]
	public partial class linqsozlukDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkelime_anlam_matriksi(kelime_anlam_matriksi instance);
    partial void Updatekelime_anlam_matriksi(kelime_anlam_matriksi instance);
    partial void Deletekelime_anlam_matriksi(kelime_anlam_matriksi instance);
    partial void InsertKullanicilar(Kullanicilar instance);
    partial void UpdateKullanicilar(Kullanicilar instance);
    partial void DeleteKullanicilar(Kullanicilar instance);
    partial void InsertKelimeAnlami(KelimeAnlami instance);
    partial void UpdateKelimeAnlami(KelimeAnlami instance);
    partial void DeleteKelimeAnlami(KelimeAnlami instance);
    partial void InsertKelimeler(Kelimeler instance);
    partial void UpdateKelimeler(Kelimeler instance);
    partial void DeleteKelimeler(Kelimeler instance);
    #endregion
		
		public linqsozlukDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SOZLUKConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqsozlukDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqsozlukDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqsozlukDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqsozlukDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<kelime_anlam_matriksi> kelime_anlam_matriksis
		{
			get
			{
				return this.GetTable<kelime_anlam_matriksi>();
			}
		}
		
		public System.Data.Linq.Table<Kullanicilar> Kullanicilars
		{
			get
			{
				return this.GetTable<Kullanicilar>();
			}
		}
		
		public System.Data.Linq.Table<KelimeAnlami> KelimeAnlamis
		{
			get
			{
				return this.GetTable<KelimeAnlami>();
			}
		}
		
		public System.Data.Linq.Table<Kelimeler> Kelimelers
		{
			get
			{
				return this.GetTable<Kelimeler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kelime_anlam_matriksi")]
	public partial class kelime_anlam_matriksi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _kelime_id;
		
		private System.Nullable<int> _kelimeAnlami_id;
		
		private EntityRef<KelimeAnlami> _KelimeAnlami;
		
		private EntityRef<Kelimeler> _Kelimeler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onkelime_idChanging(System.Nullable<int> value);
    partial void Onkelime_idChanged();
    partial void OnkelimeAnlami_idChanging(System.Nullable<int> value);
    partial void OnkelimeAnlami_idChanged();
    #endregion
		
		public kelime_anlam_matriksi()
		{
			this._KelimeAnlami = default(EntityRef<KelimeAnlami>);
			this._Kelimeler = default(EntityRef<Kelimeler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kelime_id", DbType="Int")]
		public System.Nullable<int> kelime_id
		{
			get
			{
				return this._kelime_id;
			}
			set
			{
				if ((this._kelime_id != value))
				{
					if (this._Kelimeler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkelime_idChanging(value);
					this.SendPropertyChanging();
					this._kelime_id = value;
					this.SendPropertyChanged("kelime_id");
					this.Onkelime_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kelimeAnlami_id", DbType="Int")]
		public System.Nullable<int> kelimeAnlami_id
		{
			get
			{
				return this._kelimeAnlami_id;
			}
			set
			{
				if ((this._kelimeAnlami_id != value))
				{
					if (this._KelimeAnlami.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkelimeAnlami_idChanging(value);
					this.SendPropertyChanging();
					this._kelimeAnlami_id = value;
					this.SendPropertyChanged("kelimeAnlami_id");
					this.OnkelimeAnlami_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KelimeAnlami_kelime_anlam_matriksi", Storage="_KelimeAnlami", ThisKey="kelimeAnlami_id", OtherKey="id", IsForeignKey=true)]
		public KelimeAnlami KelimeAnlami
		{
			get
			{
				return this._KelimeAnlami.Entity;
			}
			set
			{
				KelimeAnlami previousValue = this._KelimeAnlami.Entity;
				if (((previousValue != value) 
							|| (this._KelimeAnlami.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KelimeAnlami.Entity = null;
						previousValue.kelime_anlam_matriksis.Remove(this);
					}
					this._KelimeAnlami.Entity = value;
					if ((value != null))
					{
						value.kelime_anlam_matriksis.Add(this);
						this._kelimeAnlami_id = value.id;
					}
					else
					{
						this._kelimeAnlami_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("KelimeAnlami");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kelimeler_kelime_anlam_matriksi", Storage="_Kelimeler", ThisKey="kelime_id", OtherKey="id", IsForeignKey=true)]
		public Kelimeler Kelimeler
		{
			get
			{
				return this._Kelimeler.Entity;
			}
			set
			{
				Kelimeler previousValue = this._Kelimeler.Entity;
				if (((previousValue != value) 
							|| (this._Kelimeler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kelimeler.Entity = null;
						previousValue.kelime_anlam_matriksis.Remove(this);
					}
					this._Kelimeler.Entity = value;
					if ((value != null))
					{
						value.kelime_anlam_matriksis.Add(this);
						this._kelime_id = value.id;
					}
					else
					{
						this._kelime_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kelimeler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kullanicilar")]
	public partial class Kullanicilar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _adi;
		
		private string _soyadi;
		
		private string _eposta;
		
		private string _sifre;
		
		private System.Nullable<bool> _isActive;
		
		private System.Nullable<bool> _isDeleted;
		
		private System.Nullable<System.DateTime> _deleteDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnsoyadiChanging(string value);
    partial void OnsoyadiChanged();
    partial void OnepostaChanging(string value);
    partial void OnepostaChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OnisActiveChanging(System.Nullable<bool> value);
    partial void OnisActiveChanged();
    partial void OnisDeletedChanging(System.Nullable<bool> value);
    partial void OnisDeletedChanged();
    partial void OndeleteDateChanging(System.Nullable<System.DateTime> value);
    partial void OndeleteDateChanged();
    #endregion
		
		public Kullanicilar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="NVarChar(50)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyadi", DbType="NVarChar(50)")]
		public string soyadi
		{
			get
			{
				return this._soyadi;
			}
			set
			{
				if ((this._soyadi != value))
				{
					this.OnsoyadiChanging(value);
					this.SendPropertyChanging();
					this._soyadi = value;
					this.SendPropertyChanged("soyadi");
					this.OnsoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eposta", DbType="NVarChar(50)")]
		public string eposta
		{
			get
			{
				return this._eposta;
			}
			set
			{
				if ((this._eposta != value))
				{
					this.OnepostaChanging(value);
					this.SendPropertyChanging();
					this._eposta = value;
					this.SendPropertyChanged("eposta");
					this.OnepostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(50)")]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit")]
		public System.Nullable<bool> isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Bit")]
		public System.Nullable<bool> isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> deleteDate
		{
			get
			{
				return this._deleteDate;
			}
			set
			{
				if ((this._deleteDate != value))
				{
					this.OndeleteDateChanging(value);
					this.SendPropertyChanging();
					this._deleteDate = value;
					this.SendPropertyChanged("deleteDate");
					this.OndeleteDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KelimeAnlami")]
	public partial class KelimeAnlami : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _KelimeAnlami1;
		
		private string _AktiflikDurumu;
		
		private string _Dili;
		
		private System.Nullable<System.DateTime> _KayitTarihi;
		
		private System.Nullable<bool> _SilindiMi;
		
		private EntitySet<kelime_anlam_matriksi> _kelime_anlam_matriksis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnKelimeAnlami1Changing(string value);
    partial void OnKelimeAnlami1Changed();
    partial void OnAktiflikDurumuChanging(string value);
    partial void OnAktiflikDurumuChanged();
    partial void OnDiliChanging(string value);
    partial void OnDiliChanged();
    partial void OnKayitTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnKayitTarihiChanged();
    partial void OnSilindiMiChanging(System.Nullable<bool> value);
    partial void OnSilindiMiChanged();
    #endregion
		
		public KelimeAnlami()
		{
			this._kelime_anlam_matriksis = new EntitySet<kelime_anlam_matriksi>(new Action<kelime_anlam_matriksi>(this.attach_kelime_anlam_matriksis), new Action<kelime_anlam_matriksi>(this.detach_kelime_anlam_matriksis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="KelimeAnlami", Storage="_KelimeAnlami1", DbType="NVarChar(50)")]
		public string KelimeAnlami1
		{
			get
			{
				return this._KelimeAnlami1;
			}
			set
			{
				if ((this._KelimeAnlami1 != value))
				{
					this.OnKelimeAnlami1Changing(value);
					this.SendPropertyChanging();
					this._KelimeAnlami1 = value;
					this.SendPropertyChanged("KelimeAnlami1");
					this.OnKelimeAnlami1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktiflikDurumu", DbType="NVarChar(50)")]
		public string AktiflikDurumu
		{
			get
			{
				return this._AktiflikDurumu;
			}
			set
			{
				if ((this._AktiflikDurumu != value))
				{
					this.OnAktiflikDurumuChanging(value);
					this.SendPropertyChanging();
					this._AktiflikDurumu = value;
					this.SendPropertyChanged("AktiflikDurumu");
					this.OnAktiflikDurumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dili", DbType="NVarChar(50)")]
		public string Dili
		{
			get
			{
				return this._Dili;
			}
			set
			{
				if ((this._Dili != value))
				{
					this.OnDiliChanging(value);
					this.SendPropertyChanging();
					this._Dili = value;
					this.SendPropertyChanged("Dili");
					this.OnDiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> KayitTarihi
		{
			get
			{
				return this._KayitTarihi;
			}
			set
			{
				if ((this._KayitTarihi != value))
				{
					this.OnKayitTarihiChanging(value);
					this.SendPropertyChanging();
					this._KayitTarihi = value;
					this.SendPropertyChanged("KayitTarihi");
					this.OnKayitTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilindiMi", DbType="Bit")]
		public System.Nullable<bool> SilindiMi
		{
			get
			{
				return this._SilindiMi;
			}
			set
			{
				if ((this._SilindiMi != value))
				{
					this.OnSilindiMiChanging(value);
					this.SendPropertyChanging();
					this._SilindiMi = value;
					this.SendPropertyChanged("SilindiMi");
					this.OnSilindiMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KelimeAnlami_kelime_anlam_matriksi", Storage="_kelime_anlam_matriksis", ThisKey="id", OtherKey="kelimeAnlami_id")]
		public EntitySet<kelime_anlam_matriksi> kelime_anlam_matriksis
		{
			get
			{
				return this._kelime_anlam_matriksis;
			}
			set
			{
				this._kelime_anlam_matriksis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kelime_anlam_matriksis(kelime_anlam_matriksi entity)
		{
			this.SendPropertyChanging();
			entity.KelimeAnlami = this;
		}
		
		private void detach_kelime_anlam_matriksis(kelime_anlam_matriksi entity)
		{
			this.SendPropertyChanging();
			entity.KelimeAnlami = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kelimeler")]
	public partial class Kelimeler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _KelimeAdi;
		
		private string _AktiflikDurumu;
		
		private string _Dili;
		
		private System.Nullable<System.DateTime> _KayitTarihi;
		
		private System.Nullable<bool> _SilindiMi;
		
		private EntitySet<kelime_anlam_matriksi> _kelime_anlam_matriksis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnKelimeAdiChanging(string value);
    partial void OnKelimeAdiChanged();
    partial void OnAktiflikDurumuChanging(string value);
    partial void OnAktiflikDurumuChanged();
    partial void OnDiliChanging(string value);
    partial void OnDiliChanged();
    partial void OnKayitTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnKayitTarihiChanged();
    partial void OnSilindiMiChanging(System.Nullable<bool> value);
    partial void OnSilindiMiChanged();
    #endregion
		
		public Kelimeler()
		{
			this._kelime_anlam_matriksis = new EntitySet<kelime_anlam_matriksi>(new Action<kelime_anlam_matriksi>(this.attach_kelime_anlam_matriksis), new Action<kelime_anlam_matriksi>(this.detach_kelime_anlam_matriksis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeAdi", DbType="NVarChar(50)")]
		public string KelimeAdi
		{
			get
			{
				return this._KelimeAdi;
			}
			set
			{
				if ((this._KelimeAdi != value))
				{
					this.OnKelimeAdiChanging(value);
					this.SendPropertyChanging();
					this._KelimeAdi = value;
					this.SendPropertyChanged("KelimeAdi");
					this.OnKelimeAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktiflikDurumu", DbType="NVarChar(50)")]
		public string AktiflikDurumu
		{
			get
			{
				return this._AktiflikDurumu;
			}
			set
			{
				if ((this._AktiflikDurumu != value))
				{
					this.OnAktiflikDurumuChanging(value);
					this.SendPropertyChanging();
					this._AktiflikDurumu = value;
					this.SendPropertyChanged("AktiflikDurumu");
					this.OnAktiflikDurumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dili", DbType="NVarChar(50)")]
		public string Dili
		{
			get
			{
				return this._Dili;
			}
			set
			{
				if ((this._Dili != value))
				{
					this.OnDiliChanging(value);
					this.SendPropertyChanging();
					this._Dili = value;
					this.SendPropertyChanged("Dili");
					this.OnDiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> KayitTarihi
		{
			get
			{
				return this._KayitTarihi;
			}
			set
			{
				if ((this._KayitTarihi != value))
				{
					this.OnKayitTarihiChanging(value);
					this.SendPropertyChanging();
					this._KayitTarihi = value;
					this.SendPropertyChanged("KayitTarihi");
					this.OnKayitTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilindiMi", DbType="Bit")]
		public System.Nullable<bool> SilindiMi
		{
			get
			{
				return this._SilindiMi;
			}
			set
			{
				if ((this._SilindiMi != value))
				{
					this.OnSilindiMiChanging(value);
					this.SendPropertyChanging();
					this._SilindiMi = value;
					this.SendPropertyChanged("SilindiMi");
					this.OnSilindiMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kelimeler_kelime_anlam_matriksi", Storage="_kelime_anlam_matriksis", ThisKey="id", OtherKey="kelime_id")]
		public EntitySet<kelime_anlam_matriksi> kelime_anlam_matriksis
		{
			get
			{
				return this._kelime_anlam_matriksis;
			}
			set
			{
				this._kelime_anlam_matriksis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kelime_anlam_matriksis(kelime_anlam_matriksi entity)
		{
			this.SendPropertyChanging();
			entity.Kelimeler = this;
		}
		
		private void detach_kelime_anlam_matriksis(kelime_anlam_matriksi entity)
		{
			this.SendPropertyChanging();
			entity.Kelimeler = null;
		}
	}
}
#pragma warning restore 1591
